### ISSUE TITLE
Ensure a recent version of Ruby is available on all build images

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#197]
As more and more gems start requiring Ruby 2.0 > 0 (in some cases 2.2.2 >= 0), it is getting hard to keep `dpl` running smoothly. By ensuring that Ruby 2.0 is available on all images, we can reduce the maintenance cost of `dpl`.

**Comment by meatballhat** [comment]
See also: https://github.com/travis-ci/travis-ci/issues/6243
