### ISSUE TITLE
go binary unavailable in non-go builds

### ISSUE THREAD

**Issue by lislis** [travis-ci/packer-templates#213]
User reported [missing Go binary or wrongly set path on HelpScout](https://secure.helpscout.net/conversation/237158512/33234/?folderId=30784)
Error message:
https://travis-ci.org/swagger-api/swagger-codegen/jobs/150961691#L3042

They also opened an issue in the public tracker https://github.com/travis-ci/travis-ci/issues/6445

They fixed the issue in their repo in this commit by installing Go themselves 
https://github.com/swagger-api/swagger-codegen/pull/3569/files
which is ⬇️ 
```
install:
  # Add Godeps dependencies to GOPATH and PATH
   - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.4 bash)"
   - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace"
   - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
```

**Comment by meatballhat** [comment]
This should now be resolved for all trusty images with `group: edge`

**Comment by solarce** [comment]
We've promoted these to group: stable approx 15:00 PST. If you see any further problems like this one, please re-open this issue.
