### ISSUE TITLE
Mongo not on dist: trusty; group: edge anymore

### ISSUE THREAD

**Issue by joepvd** [travis-ci/packer-templates#215]
Mongo not on `dist: trusty`, `group: edge` anymore. Unfortunate, since https://github.com/travis-ci/travis-ci/issues/5948#issuecomment-213784471

Reproduced:

https://travis-ci.org/joepvd/travis-experiment/builds/151175738

Helpscout: https://secure.helpscout.net/conversation/237213025/33254/?folderId=30784

**Comment by bdbai** [comment]
I used to install `mongodb-org-server` and start it manually, but now `apt-get` complains:
```bash
mongodb-org-server is already the newest version.
mongodb-org-server set to manually installed.
```
Any workaround here?

**Comment by jme783** [comment]
+1

**Comment by rubydev** [comment]
+1

**Comment by BanzaiMan** [comment]
`group: edge` is generally discontinued. Sorry about the short notice. Please drop it, and your builds will run on the stable image.

**Comment by BanzaiMan** [comment]
With https://github.com/travis-ci/travis-build/pull/818, we now recognize `mongodb` as a service name on Trusty, and start `mongod` service.

**Comment by meatballhat** [comment]
@joepvd @BanzaiMan AFAIK this can be closed.  Can you confirm? ❤️
