### ISSUE TITLE
Network prefers IPv6 to IPv4

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#216]
https://github.com/travis-ci/travis-ci/issues/6449

**Comment by solarce** [comment]
- [ ] remove IPv6 _stuff_ from cloud-init via chef
- [ ] disable IPv6 via `sysctl` inside the GCE instance, near the beginning of a GCE packer build

**Comment by BanzaiMan** [comment]
Some software (such as [selenium-web-driver](https://github.com/goinstant/ruby-selenium-webdriver/blob/98d635539dd19437eb85566b393c1dcd0e6ebd29/lib/selenium/webdriver/common/platform.rb#L169)) has `localhost` hardcoded. This bypasses the `sysctl` fix above and goes directly to `/etc/hosts`.

https://github.com/travis-ci/travis-build/commit/d89613516ec7e7344cb9e722e07ae11e43821821 is an attempt to get around this problem by removing `localhost` from IPv6 addresses in `/etc/hosts`. This has been deployed to .org and .com production. (See https://travis-ci.org/BanzaiMan/travis_production_test/builds/151396407#L225-L232.)

**Comment by solarce** [comment]
Shipped and in production
