### ISSUE TITLE
node_js feature in build env images - reporting missing `npm install`

### ISSUE THREAD

**Issue by Lyoness** [travis-ci/packer-templates#218]
From helpscout 

I solved the problem by adding `npm install` to our 'install' script, but this used to happen automatically for projects that have 'node_js' defined in .travis.yml. Was this an intentional change?

**Comment by meatballhat** [comment]
Any job links available? 😁

**Comment by acnagy** [comment]
https://secure.helpscout.net/conversation/237027128/33175/?folderId=30788

**Comment by meatballhat** [comment]
What I'm seeing is that the affected build ran on EC2/Docker, which is not (yet) covered by this repo, nor was affected by GCE image availability issues.  :tada: ❓
