### ISSUE TITLE
Xlib extension GLX missing

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#220]
https://travis-ci.org/OGRECave/ogre/jobs/151073923#L4156
https://travis-ci.org/starviewer-medical/starviewer/jobs/150746360
https://travis-ci.org/d-meiser/qtopengl/builds/151384137

**Comment by BanzaiMan** [comment]
https://travis-ci.org/widelands/widelands/jobs/152212970#L6575

**Comment by meatballhat** [comment]
Affected images from above links:
- travis-ci-sugilite-trusty-1470771552
- travis-ci-sugilite-trusty-1470806235
- travis-ci-sugilite-trusty-1471030934

**Comment by SirVer** [comment]
Is this already rolled out? I still see the same issues in my travis builds.

**Comment by solarce** [comment]
This has not been put into production, you can test it by adding `group: edge` to your `.travis.yml`, we hope to have promote it to the stable image on Monday.

**Comment by SirVer** [comment]
Will this thread be updated once this is in production? Monday sounds great to me, so I'll wait till then.

**Comment by meatballhat** [comment]
@SirVer Sorry for delay!  We're prepping a promotion of the images with the fix to `group: stable` (the default) tomorrow 2016-08-24.

**Comment by SirVer** [comment]
My tests just passed again, so the rollout seems to have been successful. Thanks for your help with this, travis team.
