### ISSUE TITLE
Ensure python 3.5.x is available

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#223]
Currently we do not install it yet.

**Comment by meatballhat** [comment]
@BanzaiMan on which stack(s)? 😁

**Comment by BanzaiMan** [comment]
Eh… all of them? 😮  Any image that should contain multiple Python images, I'm thinking.

**Comment by meatballhat** [comment]
@BanzaiMan rn that's the precise `python` stack and both `garnet` and `sugilite` trusty stacks.  Does that cover it?

**Comment by BanzaiMan** [comment]
Yes.

**Comment by meatballhat** [comment]
@BanzaiMan As it turns out, 3.5.2 is currently being preinstalled on GCE+python and GCE+garnet, and 3.5.0 is being preinstalled on GCE+sugilite.  The docker execution envs will benefit from this once we roll out the updated infrastructure over there.  I'm going to get GCE+sugilite updated to 3.5.2.
