### ISSUE TITLE
Install postgresql-9.3-postgis-scripts

### ISSUE THREAD

**Issue by emdantrim** [travis-ci/packer-templates#224]
Per HS #33300

**Comment by meatballhat** [comment]
Affected job: https://travis-ci.org/inaturalist/inaturalist/jobs/151354171 (travis-ci-sugilite-trusty-1470806235)

**Comment by Lyoness** [comment]
Postgis issue here, could maybe have predated trusty outage: 

https://github.com/travis-ci/travis-ci/issues/5178
https://github.com/travis-ci/travis-ci/issues/5509

Patch/fix here:  https://github.com/travis-ci/travis-cookbooks/pull/646

HS #33588
