### ISSUE TITLE
Install cassandra on new sudo-enabled Trusty stacks

### ISSUE THREAD

**Issue by cotsog** [travis-ci/packer-templates#229]
We've received some tickets:

https://secure.helpscout.net/conversation/237217592/33256/?folderId=504985
https://secure.helpscout.net/conversation/237108001/33214/?folderId=30784

Here's [a test build](https://travis-ci.org/cotsog/travis_ci_prod_trusty/builds/151389400) I did ([.travis.yml file here](https://github.com/cotsog/travis_ci_prod_trusty/blob/3990dbc7b68fc3cd059194d7a6fca3b1cc0d2bb6/.travis.yml)).

Thank you! 💙

**Comment by meatballhat** [comment]
@cotsog Do I understand correctly that this is a regression fix for Ubuntu Precise stacks and a feature request for Ubuntu Trusty stacks?

**Comment by cotsog** [comment]
@meatballhat: I double-checked and it seems I was wrong wrt to Cassandra's status on Precise. I think I was confused by [the `cat: /var/run/cassandra.pid: No such file or directory` message](https://travis-ci.org/cotsog/travis_ci_prod_trusty/jobs/152298638#L120). Checking the status of the Cassandra service in the `script:` section [shows it's indeed running](https://travis-ci.org/cotsog/travis_ci_prod_trusty/jobs/152298638#L141-L142).

I also wrongfully thought that Cassandra was available on the old Trusty images. But looking at the docs showed me [that it wasn't](https://docs.travis-ci.com/user/trusty-ci-environment#Data-Stores).

Hence, I believe you can keep the ticket as a feature request for having Cassandra available on Trusty. FWIW, one of the customer asking about it was Zendesk. However, you may close this issue if this is tracked somewhere else.

Thank you again and sorry for the confusion.

**Comment by meatballhat** [comment]
@cotsog Thanks for the clarification! 😻
