### ISSUE TITLE
Ensure the image has a reasonable PHP runtime as default

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#244]
https://github.com/travis-ci/travis-ci/issues/6451

Be sure to run `phpenv global 5.6` (or whatever is appropriate) after setting up all PHP runtimes.

**Comment by meatballhat** [comment]
Reported on images:
- travis-ci-sugilite-trusty-1470690394

**Comment by meatballhat** [comment]
Is setting `7.0.7` as the default OK, or should I stick to the `5.6.x` series?
