### ISSUE TITLE
Incomplete PostgreSQL 9.5 installation

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#255]
https://secure.helpscout.net/conversation/240457382/0/?folderId=30784

The current Precise image is a bit off with respect to PostgreSQL packages. This is causing `pg_config --bindir` to report an incorrect value.

In particular, `postgresql-client-9.5` is installed, while no other 9.5 packages are.

Either not install this package at all, or install all the relevant 9.5 packages.

I think this is a fairly serious issue that should be addressed very soon.

These steps should fix the issue on the fly:

```
sudo apt-get purge postgresql-client-9.5
sudo apt-get install postgresql-server-dev-9.4
```

(Might be worth doing in `travis-build`, but the real fix should come from the images themselves.)

**Comment by BanzaiMan** [comment]
If all 9.5 packages are to be installed, be sure to update the docs! (a la https://github.com/travis-ci/docs-travis-ci-com/pull/701).

**Comment by meatballhat** [comment]
I think this *may* be happening because the `postgresql-client` metapackage now points to the 9.5 client, at least in the pgdg repo:

```
--- >8 ---

Package: postgresql-client
Source: postgresql-common (175.pgdg14.04+1)
Version: 9.5+175.pgdg14.04+1
Architecture: all
Maintainer: Debian PostgreSQL Maintainers <pkg-postgresql-public@lists.alioth.debian.org>
Installed-Size: 52
Depends: postgresql-client-9.5
Multi-Arch: foreign
Priority: optional
Section: database
Filename: pool/main/p/postgresql-common/postgresql-client_9.5+175.pgdg14.04+1_all.deb

--- >8 ---
```
