### ISSUE TITLE
Ensure SSL connection is enabled for PostgreSQL on container images

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#256]
https://github.com/travis-ci/travis-ci/issues/5753
A hot fix: https://github.com/travis-ci/travis-build/pull/795

**Comment by meatballhat** [comment]
As far as I can tell, this is already the case, at least for the PostgreSQL packages installed and managed via cookbooks and packer.

Here are the relevant bits on the cookbooks `master` branch, which is roughly the same story for the `precise-stable` branch:

- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/attributes/default.rb#L9
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/9.6/postgresql.conf.erb#L79
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/9.5/postgresql.conf.erb#L81
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/9.4/postgresql.conf.erb#L81
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/9.3/postgresql.conf.erb#L81
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/9.2/postgresql.conf.erb#L80
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/9.1/postgresql.conf.erb#L80
- https://github.com/travis-ci/travis-cookbooks/blob/58fad1f3581f47f7f1a198be3810b873353235ad/cookbooks/postgresql/templates/ubuntu/8.4/postgresql.conf.erb#L78

**Comment by BanzaiMan** [comment]
I can't reproduce the original problem.

Closing this.
