### ISSUE TITLE
Bump default PostgreSQL versions to 9.3-9.6

### ISSUE THREAD

**Issue by joshk** [travis-ci/packer-templates#301]
I think it would be fine to have our defaults installed being 9.3, 9.4, 9.5 and 9.6

This feature request comes from some people at Heroku, as well as a travis-ci/travis-ci issue.

How long would this update possibly take to be available?

**Comment by BanzaiMan** [comment]
For reference: https://github.com/travis-ci/travis-ci/issues/4264#issuecomment-250499199

**Comment by meatballhat** [comment]
@joshk Is this wanted on precise as well as trusty?  I would like to minimize changes to precise if possible, so if trusty is good enough that'd be rad 🤘

**Comment by joshk** [comment]
Only Trusty is fine by me!

**Comment by meatballhat** [comment]
Incoming https://travis-ci.org/meatballhat/cloaked-octo-tyrion/jobs/174533645

**Comment by meatballhat** [comment]
This is now generally available on Trusty container-based, and in Trusty fully-virtualized with `group: edge`.

- https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/174742927
- https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/174743270

**Comment by joshk** [comment]
@meatballhat you rock!

When do you expect this to be available in the Trusty containers and in stable?
