### ISSUE TITLE
Update git to 2.x

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#303]
With https://github.com/travis-ci/dpl/pull/516, we can now use `git` 2.10.x to deploy to Heroku via `git`. I do not think there is any other reason to stay on `git` 1.9.x now.

- [x] sudo-enabled Trusty
- [x] <del>sudo-enabled Precise</del>
- [ ] container-based Trusty
- [x] <del>container-based Precise</del>

Related to https://github.com/travis-ci/travis-ci/issues/6328

**Comment by Lyoness** [comment]
OHAI<

Gathering upstream/downstream/sidestream changes/links to test a PR for `git` 2.10.x 

https://github.com/travis-ci/packer-templates/blob/b21843a4a55a44fd87be23affbfe0405fc043d38/cookbooks/lib/features/git_spec.rb#L9

https://github.com/travis-ci/packer-templates/blob/96f194a8d63a372a65983a7dd7e45771552f4937/Gemfile.lock

https://github.com/travis-ci/travis-cookbooks/blob/7c319e84b14824a19b027bf65ed737d40fe8c671/cookbooks/travis_git/recipes/ppa.rb

https://github.com/travis-ci/travis-packer-build/blob/c816b9749f1864a647b4deb873d8494bfa94eaaa/travis-packer-build.gemspec#L26

**Comment by BanzaiMan** [comment]
I'll release dpl with the fix above some time next week, long before the images are released to the public.

**Comment by BanzaiMan** [comment]
`dpl` 1.8.22 has been released.

**Comment by Lyoness** [comment]
https://github.com/travis-ci/travis-cookbooks/blob/64ff883360f3d265b87c072a07f78e9ef0a874fb/community-cookbooks/git/attributes/default.rb

**Comment by meatballhat** [comment]
This is pretty straightforward for Trusty, but I'd like to avoid anything other than security updates for Precise.

**Comment by BanzaiMan** [comment]
@meatballhat That's fine with me, as far as I'm concerned. I don't think anything would break by staying with git < 2 on Precise.

**Comment by meatballhat** [comment]
Looking good on the connie stack.  Triggering builds for remaining trusty stacks.  :+1: https://travis-ci.org/meatballhat/cloaked-octo-tyrion/jobs/177726602#L125

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
It is my understanding that this update will also bump from 1.8 to 1.9 on precise, correct?

**Comment by meatballhat** [comment]
@igorwwwwwwwwwwwwwwwwwwww sorry for huge delay.  Looking like precise remains on 1.8: https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/builds/534409#L24-L25

``` bash
$ git --version
git version 1.8.5.6
```

**Comment by ryanhugh** [comment]
Any update on this? The latest version of gh-pages (https://www.npmjs.com/package/gh-pages) no longer supports git < 1.9. In the Travis containers the git version is still version 1.8.5.6.
