### ISSUE TITLE
Add image for Dart

### ISSUE THREAD

**Issue by a14n** [travis-ci/packer-templates#314]
I can't find a Dart image on [quay.io](https://quay.io/organization/travisci). Could you please add it? (or explain what should be done to help me create a PR)

**Comment by meatballhat** [comment]
@a14n Hello!  Sorry for the big delay.  Jobs with `language: dart` currently route to the stack image designated `language: default`, which is the [Ruby stack image](https://quay.io/repository/travisci/travis-ruby) for Ubuntu 12.04 Precise and the [Garnet stack image](https://hub.docker.com/r/travisci/ci-garnet/) for Ubuntu 14.04 Trusty.  I hope this helps!  Please holler if you feel this issue should be reopened :heart:

**Comment by a14n** [comment]
I don't really understand.

Do you mean I have to use `quay.io/travisci/travis-ruby` or `https://hub.docker.com/r/travisci/ci-garnet` when I want to debug locally as describe in https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally ?

**Comment by BanzaiMan** [comment]
Hi, @a14n, yes, that's exactly what @meatballhat meant.
