### ISSUE TITLE
Upgrade worker instance kernel to alleviate unregister_netdevice issues

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/packer-templates#338]
As described in this docker issue: https://github.com/docker/docker/issues/5618

Switching to a recent mainline kernel is expected to remove the ongoing issues we have been experiencing with `unregister_netdevice`.

- ubuntu mainline build wiki page: https://wiki.ubuntu.com/Kernel/MainlineBuilds
- mainline kernel PPA downloads for 4.8.7: http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.8.7/

**Comment by meatballhat** [comment]
I manually upgraded the kernel on a few staging worker instances, rebooting afterward.  I threw a bunch of jobs at both Trusty and Precise images, and no `unregister_netdevice` errors were detected:

- https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/jobs/515864
- https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/jobs/516693

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
❤️ ❤️ ❤️

**Comment by meatballhat** [comment]
I'm still prepared to be surprised in production, given the variety of workload thrown at us there.  🎱
