### ISSUE TITLE
Add yarn

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#344]
We've rolled out Yarn support today (2016-11-21). It would be great if we can have it preinstalled. The current `yarn` installation step will be simply skipped if it is available already.

Either `apt` + `brew` or `curl | bash` works for installation (https://yarnpkg.com/en/docs/install); the current on-demand installation uses the latter.

- [x] sudo-enabled Trusty
- [ ] container-based Trusty

**Comment by tristanbes** [comment]
Especially when we have not a `nodejs` project.

For example, installing manually `yarn` for `php` project will result in the PGP keyserver *not responding* 1/3 of the time which is REALLY annoying.

So i'm 👍

**Comment by outerim** [comment]
We're currently manually installing `npm install -g yarn` 😱 on our container based `language: ruby` builds. Seems to work OK for now but would happily switch to the default install when available.
