### ISSUE TITLE
MySQL root user with no password not working anymore

### ISSUE THREAD

**Issue by cotsog** [travis-ci/packer-templates#350]
With the release of the new GCE Trusty images, [a customer wrote](https://secure.helpscout.net/conversation/285862957/45260/?folderId=576125) to let us know that using the `root` user with no password in MySQL 5.6 doesn't work anymore.

[Since this is currently documented](https://docs.travis-ci.com/user/database-setup/#MySQL-5.6), would it be possible to fix this?

Thanks!

**Comment by cotsog** [comment]
[Users chimed in](https://github.com/travis-ci/travis-ci/issues/6961#issuecomment-264283390) on the public issue tracking the MySQL situation on the new GCE Trusty images.

> Looks like the empty password is not set for root@localhost (it's only set for root@127.0.0.1 which is not the same).
>
>This workaround in before_install seems to work:
>
> `mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"`

**Comment by meatballhat** [comment]
This should be fixed as of https://docs.travis-ci.com/user/build-environment-updates/2016-12-02/ :+1:
