### ISSUE TITLE
Pre-install git-lfs on all images

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#386]

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/

**Comment by meatballhat** [comment]
AFAIK this is the case 👍  Please yell/reopen if not.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/BanzaiMan/travis_production_test/builds/194939009 leads me to believe that this is still a problem in all but GCE Trusty.

**Comment by BanzaiMan** [comment]
Not having it on Precise is acceptable; we just have to document it.

**Comment by meatballhat** [comment]
@BanzaiMan I'm confused about the reopening of the issue, then 😕

**Comment by BanzaiMan** [comment]
@meatballhat GCE Trusty doesn't have one. https://travis-ci.org/BanzaiMan/travis_production_test/jobs/194939013 (or, do I need to test the Edge image?)

**Comment by meatballhat** [comment]
@BanzaiMan :woman_facepalming: https://github.com/travis-ci/travis-cookbooks/pull/828

**Comment by nicolas-albert** [comment]
No updates about this ? I use a "trusty" dist and I don't success to 'git lfs pull'.
