### ISSUE TITLE
Make it easier to switch Java versions in non-java builds

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#388]
ElasticSearch, in particular, could require Java 8.

In languages other than `java` and `ruby`, this could pose a problem when the default version does not satisfy this requirement, because `jdk_switcher` is not run during the build, and the `jdk_switcher` function is not made available if the source file is not available.

**Comment by meatballhat** [comment]
@BanzaiMan Which source file isn't available?

**Comment by BanzaiMan** [comment]
On Java image, we have:

```sh-session
$ cat /etc/profile.d/load_jdk_switcher.sh
#!/bin/sh

# if jdk_switcher is provisioned (typically part of java::multi recipe),
# load it
if test -f $HOME/.jdk_switcher_rc; then
    . $HOME/.jdk_switcher_rc
fi
```

These are the files I meant.

Upon further investigation, though, Trusty images do have these files, it appears (I've only tested PHP) that we don't have to worry about this one.
