### ISSUE TITLE
Update Android components

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#390]
This corresponds to https://github.com/travis-ci/travis-ci/issues/6279.

The components are undoubtedly updated since the issue above was opened, and we need to ensure that a reasonable set exists on our Android image.

**Comment by BanzaiMan** [comment]
Perhaps this replaces #294?

**Comment by meatballhat** [comment]
@BanzaiMan Is the list of components in travis-ci/travis-ci#6279 complete, meaning everything on the list should be included and anything *not* on the list should be excluded?

**Comment by BanzaiMan** [comment]
To be quite honest, I don't know what constitutes a complete list in this context. Probably we need expert advice.

**Comment by MGaetan89** [comment]
@meatballhat The list I provided in travis-ci/travis-ci#6279 is only the list of components currently missing on Travis. I think that the components that are already preinstalled can stay.

However, Google marked some components as "Obsolete" in the SDK Manager in Android Studio. So maybe those can be deprecated/removed if needed.
For the system images, everything before API 15 (excluded) is marked as obsolete (so API 1-14).
For the Build Tools, here is the full list:
![screenshot from 2017-01-26 07-19-22](https://cloud.githubusercontent.com/assets/1009664/22321804/e39f3f8e-e397-11e6-8364-ec7a33021f68.png)

**Comment by MGaetan89** [comment]
@BanzaiMan @meatballhat Is there something else I can provide/do to help you move forward with this?

**Comment by solarce** [comment]
Hiro is currently traveling and Dan is focused on some other urgent stability related work, so it'll be a week or two before you can expect to hear anything further back on this issue. Sorry for the delays.

**Comment by MGaetan89** [comment]
@solarce Ok, no problem. Thanks for the info.

**Comment by MGaetan89** [comment]
In case you also want to support Developer Preview of Android, the following components are now also available:
- Build tools 26-rc1
- sys-img-x86-android-26
- sys-img-x86_64-android-26

**Comment by MGaetan89** [comment]
Build Tools 25.0.3 is now available as well.

**Comment by MGaetan89** [comment]
We now have:
- Build Tools 26.0.0-rc2
- Updated system images for Android O

Any update on your side?

**Comment by Lyoness** [comment]
https://github.com/travis-ci/packer-templates/pull/437

Android-only image in active dev for trusty

Cookbook here: https://github.com/travis-ci/travis-cookbooks/pull/838

**Comment by MGaetan89** [comment]
@Lyoness Thanks for the update. Looking forward to the release.

**Comment by MGaetan89** [comment]
Build Tools 26 is now available.

**Comment by Lyoness** [comment]
Ah yes @MGaetan89,  they are currently available in our `group: edge` 

```
language: android
dist: trusty

group: edge
```

Full list of components (here)[https://travis-ci.com/travis-pro/test-project#L342]

**Comment by MGaetan89** [comment]
Thanks for the info @Lyoness. That's awesome news!
Unfortunately I can not access the link you provide. Could you list the components here?

**Comment by Lyoness** [comment]
@MGaetan89 

```
List of Android SDK components that can be specified in .travis.yml
addon-google_apis-google-10
addon-google_apis-google-11
addon-google_apis-google-12
addon-google_apis-google-13
addon-google_apis-google-14
addon-google_apis-google-15
addon-google_apis-google-16
addon-google_apis-google-17
addon-google_apis-google-18
addon-google_apis-google-19
addon-google_apis-google-21
addon-google_apis-google-22
addon-google_apis-google-23
addon-google_apis-google-24
addon-google_apis-google-3
addon-google_apis-google-4
addon-google_apis-google-5
addon-google_apis-google-6
addon-google_apis-google-7
addon-google_apis-google-8
addon-google_apis-google-9
addon-google_gdk-google-19
addon-google_tv_addon-google-12
addon-google_tv_addon-google-13
android-10
android-11
android-12
android-13
android-14
android-15
android-16
android-17
android-18
android-19
android-2
android-20
android-21
android-22
android-23
android-24
android-25
android-3
android-4
android-5
android-6
android-7
android-8
android-9
build-tools-17.0.0
build-tools-18.0.1
build-tools-18.1.0
build-tools-18.1.1
build-tools-19.0.0
build-tools-19.0.1
build-tools-19.0.2
build-tools-19.0.3
build-tools-19.1.0
build-tools-20.0.0
build-tools-21.0.0
build-tools-21.0.1
build-tools-21.0.2
build-tools-21.1.0
build-tools-21.1.1
build-tools-21.1.2
build-tools-22.0.0
build-tools-22.0.1
build-tools-23.0.0
build-tools-23.0.1
build-tools-23.0.2
build-tools-23.0.3
build-tools-24.0.0
build-tools-24.0.1
build-tools-24.0.2
build-tools-24.0.3
build-tools-25.0.0
build-tools-25.0.1
build-tools-25.0.2
build-tools-25.0.3
build-tools-26.0.0-preview
doc-24
extra-android-m2repository
extra-google-admob_ads_sdk
extra-google-analytics_sdk_v2
extra-google-auto
extra-google-gcm
extra-google-google_play_services
extra-google-google_play_services_froyo
extra-google-instantapps
extra-google-m2repository
extra-google-market_apk_expansion
extra-google-market_licensing
extra-google-play_billing
extra-google-simulators
extra-google-webdriver
platform-tools
platform-tools-preview
source-14
source-15
source-16
source-17
source-18
source-19
source-20
source-21
source-22
source-23
source-24
source-25
sys-img-arm64-v8a-android-24
sys-img-arm64-v8a-google_apis-24
sys-img-arm64-v8a-google_apis-25
sys-img-armeabi-v7a-android-10
sys-img-armeabi-v7a-android-14
sys-img-armeabi-v7a-android-15
sys-img-armeabi-v7a-android-16
sys-img-armeabi-v7a-android-17
sys-img-armeabi-v7a-android-18
sys-img-armeabi-v7a-android-19
sys-img-armeabi-v7a-android-21
sys-img-armeabi-v7a-android-22
sys-img-armeabi-v7a-android-24
sys-img-armeabi-v7a-android-tv-21
sys-img-armeabi-v7a-android-tv-22
sys-img-armeabi-v7a-android-tv-23
sys-img-armeabi-v7a-android-wear-23
sys-img-armeabi-v7a-android-wear-25
sys-img-armeabi-v7a-google_apis-10
sys-img-armeabi-v7a-google_apis-15
sys-img-armeabi-v7a-google_apis-16
sys-img-armeabi-v7a-google_apis-17
sys-img-armeabi-v7a-google_apis-18
sys-img-armeabi-v7a-google_apis-19
sys-img-armeabi-v7a-google_apis-21
sys-img-armeabi-v7a-google_apis-22
sys-img-armeabi-v7a-google_apis-23
sys-img-armeabi-v7a-google_apis-24
sys-img-armeabi-v7a-google_apis-25
sys-img-mips-android-15
sys-img-mips-android-16
sys-img-mips-android-17
sys-img-x86-android-10
sys-img-x86-android-15
sys-img-x86-android-16
sys-img-x86-android-17
sys-img-x86-android-18
sys-img-x86-android-19
sys-img-x86-android-21
sys-img-x86-android-22
sys-img-x86-android-23
sys-img-x86-android-24
sys-img-x86-android-tv-21
sys-img-x86-android-tv-22
sys-img-x86-android-tv-23
sys-img-x86-android-tv-24
sys-img-x86-android-tv-25
sys-img-x86-android-wear-23
sys-img-x86-android-wear-25
sys-img-x86-google_apis-10
sys-img-x86-google_apis-15
sys-img-x86-google_apis-16
sys-img-x86-google_apis-17
sys-img-x86-google_apis-18
sys-img-x86-google_apis-19
sys-img-x86-google_apis-21
sys-img-x86-google_apis-22
sys-img-x86-google_apis-23
sys-img-x86-google_apis-24
sys-img-x86-google_apis-25
sys-img-x86-google_apis_playstore-24
sys-img-x86_64-android-21
sys-img-x86_64-android-22
sys-img-x86_64-android-23
sys-img-x86_64-android-24
sys-img-x86_64-google_apis-21
sys-img-x86_64-google_apis-22
sys-img-x86_64-google_apis-23
sys-img-x86_64-google_apis-24
sys-img-x86_64-google_apis-25
tools
which android && echo -e "\033[33;1mSee http://docs.travis-ci.com/user/languages/android/#How-to-install-Android-SDK-components\033[0m"
/usr/local/android-sdk/tools/android
See http://docs.travis-ci.com/user/languages/android/#How-to-install-Android-SDK-components
```

**Comment by MGaetan89** [comment]
@Lyoness Thank you for the list. I tried to update my Travis configuration, but I ended up with the following error (which is already reported in https://github.com/travis-ci/travis-ci/issues/6843):
`The command "jdk_switcher use oraclejdk8" failed and exited with 127 during .`
([associated build](https://travis-ci.org/MGaetan89/ShowsRage/jobs/241275451))

So I will wait until it is available in a stable state.

**Comment by Lyoness** [comment]
Hello @MGaetan89 

Ah, yes. @MGaetan89 -- Sorry I wasn't explicit before:  Due to the large number of android components/SDKs, the new Android image developed for trusty _currently does not fit in a docker image_,  which is our `sudo: false` image, and running in Docker. 

For now, this `edge` image is only available in a full VM on our GCE infrastructure ( you'll need to specify `sudo: required` or delete your `sudo: false` in your .travis.yml to get it).   

We are currently gathering feedback from our Android users regarding which tools/components/SDKs we can purge for a trusty android to fit in a docker image.

**Comment by MGaetan89** [comment]
Thank you for the detail @Lyoness. I will try again when I have time.

In https://github.com/travis-ci/packer-templates/issues/390#issuecomment-275316231, I listed the components that are obsoletes according to Google. Maybe that can be a starting point.
User can always install them manually if necessary, right?

**Comment by MGaetan89** [comment]
I just tried again. But I get `The command "android-update-sdk --components=android-25" failed and exited with 127 during .`.
You can see the changes I made in https://github.com/MGaetan89/Tetrinet/commit/0022c82fc4fd6dbe7e6e266223540333d1892c0f, and the associated [build](https://travis-ci.org/MGaetan89/Tetrinet/builds/245644060).

**Comment by Lyoness** [comment]
https://github.com/travis-pro/team-sapphire/issues/492

**Comment by Lyoness** [comment]
@MGaetan89 ... we shipped updates to this, can you try again?

**Comment by Lyoness** [comment]
I'm going to close this, since [ci-cookiecat (our new Android image for Trusty)](https://github.com/travis-ci/packer-templates/blob/master/ci-cookiecat.yml) has been available in prod.  I'd like to track _new_ issues relating to this Android image to focus on specific fixes needed to get out of beta.
