### ISSUE TITLE
Upgrade jq to 1.5

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#392]
See https://github.com/travis-ci/travis-ci/issues/7025

**Comment by meatballhat** [comment]
@BanzaiMan The stacks you tagged are precise *only*.  Is that intentional?  If possible, I'd like to ship upgrades like this only to trusty.

**Comment by meatballhat** [comment]
I'd like to avoid anything other than security updates for Precise, and the Trusty stacks already have jq 1.5.  I've updated travis-ci/travis-ci#7025 accordingly 🤘
