### ISSUE TITLE
Pre-install (but not default to) Ruby 2.4.0 with alias 2.4 on all build images

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#393]
See https://github.com/travis-ci/travis-ci/issues/7077

**Comment by meatballhat** [comment]
Same question as https://github.com/travis-ci/packer-templates/issues/392#issuecomment-270798933 😕

**Comment by meatballhat** [comment]
This is in place, and will be available on both container-based and sudo-enabled in the upcoming build environment update.

**Comment by Lyoness** [comment]
@svenfuchs , FYI on your request for 2.4 ruby ^^
