### ISSUE TITLE
Update default Node.js version 

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#394]
See https://github.com/travis-ci/travis-ci/issues/7108

As of today, LTS is pointing to 6.9.3, so that seems like a reasonable choice.

The change in default would involve `travis-build`, and it may break a few Node.js builds, but in general, the Node.js developers want to keep up with the current version, and they tend to explicitly specify Node.js versions to run.

**Comment by meatballhat** [comment]
Same question as https://github.com/travis-ci/packer-templates/issues/392#issuecomment-270798933 😕
