### ISSUE TITLE
Update Node.js version on Java Image

### ISSUE THREAD

**Issue by acnagy** [travis-ci/packer-templates#401]
A kind person (@boennemann) asked us on [Twitter](https://twitter.com/user/status/821683598797443073) updating the node version shipped on the Java image. Right now, it's at [0.10.36](https://travis-ci.org/acnagy/sketchbook/builds/193047902#L158), which has also reached end-of-life. Bringing node here up to a more current version would be perfect 👌

**Comment by meatballhat** [comment]
If this is specific to the Precise stack(s), then I think the solution is going to be an explicit operation with `nvm` to get the desired node version.  The Precise stack(s) are only getting security updates from now on, if I can help it.  The Trusty stacks all have more recent node versions installed and set as default, fwiw: https://docs.travis-ci.com/user/trusty-ci-environment ❤️
