### ISSUE TITLE
Trusty image needs a new version of RabbitMQ

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#403]
https://github.com/travis-ci/travis-ci/issues/7195 brought to light that our Trusty image does not have a recent version of RabbitMQ.

The Precise image has 0.5.2, but the Trusty image has 0.4.1 (which I believe comes from the official repository (http://packages.ubuntu.com/trusty/librabbitmq1). This suggests the Precise one is coming from another source; we need this adapted to Trusty.

**Comment by BanzaiMan** [comment]
Actually, php-src-builder is installing `librabbitmq-dev`. With Precise, [it depends on librabbitmq0](http://packages.ubuntu.com/precise/librabbitmq-dev), and is version 0.0.1.hg216-1; on Trusty, [it depends on librabbitmq1](http://packages.ubuntu.com/trusty/librabbitmq-dev), and is version 0.4.1-1.

**Comment by stof** [comment]
Well, you could get a new version of librabbitmq. 

https://deb.sury.org/ (which provides newer versions of PHP for both Debian and Ubuntu, by the maintainer of the Debian packaging of PHP) contains a librabbitmq4 package, precisely because Trusty ships a totally outdated version of librabbitmq

**Comment by stof** [comment]
@BanzaiMan this is handled by the PHP cookbook. Here is how it looks like in the ``precise-stable`` branch: https://github.com/travis-ci/travis-cookbooks/blob/479d954150e4f23dd63cedb5d410799f9bc649e1/ci_environment/php/attributes/default.rb#L50

**Comment by BanzaiMan** [comment]
@stof That is how php-src-builder compiles the extension. https://github.com/travis-ci/php-src-builder/blob/0add2c2f31195069f410757b31a687ff4b9c89d8/bin/compile-extension-amqp

If you want to add the PPA source indicated in https://deb.sury.org/, you can do that with the `apt` addon with `sudo: required`. In that case, though, you might want to use the PHP runtime this PPA provides, so that you have a clearer idea of what your builds depend on.

**Comment by stof** [comment]
@BanzaiMan on Precise, the cookbook brings a custom version of librabbitmq instead of using the official repository, because the official repo contains a very old one (due to the distro being an old one and not updating the library in it since the release...). Why not doing the same for Trusty, so that compilation works ?

**Comment by stof** [comment]
btw, the extension compilation even seems to compile the latest librabbitmq itself (after *also* installing the APT package).
So it should probably ensure that the extension is compiled against the custom lib rather than the APT one *and* that the custom one is shipped along the extension.
