### ISSUE TITLE
Missing OpenJDK 7

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#411]
https://github.com/travis-ci/travis-ci/issues/7019#issuecomment-275672662

After fixing the spot to call to `jdk_switcher` on Trusty container, the actual switch is incomplete because [many alternatives do not exist](https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/538322#L414-L445).

<details>
<pre>
$ jdk_switcher use openjdk7
Switching to OpenJDK7 (java-1.7.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-7-openjdk-amd64
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/appletviewer
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/extcheck
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/idlj
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jarsigner
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jar
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/javadoc
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/javah
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/javap
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jcmd
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jconsole
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jdb
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jhat
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jinfo
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jmap
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jps
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jrunscript
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jsadebugd
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jstack
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jstatd
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/jstat
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/native2ascii
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/rmic
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/schemagen
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/serialver
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/wsgen
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/wsimport
update-java-alternatives: jdk alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/bin/xjc
update-alternatives: error: alternative /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/policytool for policytool not registered; not setting
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
</pre>
</details>

Many of these (if not all) are essential development tools (such as `javac`, `jhat`).

**Comment by BanzaiMan** [comment]
The issue manifests on the GCE image as well. https://staging.travis-ci.org/BanzaiMan/travis_staging_test/jobs/538323

**Comment by bogdanap** [comment]
This seems to have been fixed in the meantime: https://travis-ci.org/bogdanap/travis_production_test/builds/295243401
