### ISSUE TITLE
Ensure i386 is added as a foreign architecture

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#427]
See https://github.com/travis-ci/travis-ci/issues/7558

We can add a hot fix with `travis-build`, but it should be ideally avoided.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-build/pull/1022 for the temporary fix with `travis-build`.

**Comment by Lyoness** [comment]
https://github.com/travis-ci/travis-cookbooks/blob/dd9f5788f0b4142a9f8fe61962a6dc5e924f6f1a/cookbooks/travis_build_environment/attributes/default.rb#L137
