### ISSUE TITLE
Update `precise` version of `libssl1.0.0`

### ISSUE THREAD

**Issue by staticfloat** [travis-ci/packer-templates#428]
Hey there,

On the `precise` images (such as the image downloadable via `docker run -ti 'quay.io/travisci/travis-ruby'`), the `libssl1.0.0` version is too old for TLS, which is causing problems with many sites as they start to transition away from SSLv3 and TLS 1.0.  For instance, Fastly (which GitHub is based on top of) [has just moved](https://www.fastly.com/blog/phase-two-our-tls-10-and-11-deprecation-plan) the majority of their customers over to TLS 1.2+ (GitHub appears to be an exception, but won't be for more than about a year at most).

Currently, we can work around this using `sudo apt-get update && sudo apt-get install -y libssl1.0.0`.

**Comment by meatballhat** [comment]
@staticfloat Hello!  I don't expect we will be modifying the stacks based on `precise` any more.
