### ISSUE TITLE
Pre-install the en_GB postgres collation

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/packer-templates#446]
(From @cotsog in travis-pro/team-blue#369 )

This was already setup on our old Bluebox Precise image, do we want to do the same on the new GCE images?

The manual recipe is here: https://github.com/mysociety/alaveteli/commit/94427c097ec44e5c48a5af1d0c542403c5f6eb8d.

**Comment by bogdanap** [comment]
This won't be added to our current images.
