### ISSUE TITLE
Ensure all build images have Ruby 2.2.x pre-installed

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#453]
While some deployment providers may be able to run on 2.3+, this is not yet fully supported (https://github.com/travis-ci/dpl/issues/513).

The current `language: generic` GCE Trusty image lacks rubies before 2.3.0, and deployment will cause this error message to appear:

```
/home/travis/.travis/job_stages: line 890: rubies_array_sorted: bad array subscript
```

In the cases I've seen this, the deployment provider is `script`, and did not cause deployment to fail, but, in general, it is not the case.

**Comment by meatballhat** [comment]
@BanzaiMan For customers who need this combination, I recommend a workaround of using a different `language` such as `language: __sugilite__`.

**Comment by meatballhat** [comment]
Related: https://github.com/travis-ci/packer-templates/pull/454

**Comment by meatballhat** [comment]
:white_check_mark: :bell:
