### ISSUE TITLE
MySQL `travis` default user configuration in Trusty

### ISSUE THREAD

**Issue by iriberri** [travis-ci/packer-templates#470]
Looks like something changed in the way the default `travis` user is configured in MySQL between Precise and Trusty environments.

I ran `mysql -e 'SELECT * FROM mysql.user;'` in both environments and the results are available at: https://gist.github.com/iriberri/1b65bd85c8e4d7bbda334e33307afe51

This change is causing errors such as the following one when switching from Precise to Trusty:

```
ActiveRecord::Migration.maintain_test_schema!
Mysql2::Error:
Access denied for user 'travis'@'%' to database xxxx
```

**Comment by cotsog** [comment]
Additional details coming from @bwells in [this ticket](https://secure.helpscout.net/conversation/401257380/57102/?folderId=30788):

> We're experience broken builds under the new trusty environment. I've tracked it down to the permissions the travis user has in the default mysql setup.
>
>Under Precise:
>
> `GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'`
>
>Under Trusty:
>
> `GRANT USAGE ON *.* TO 'travis'@'localhost'`
>
>Referring to the MySQL docs
>
>"The USAGE privilege specifier stands for "no privileges." It is used at the global level with GRANT to modify account attributes such as resource limits or SSL characteristics without naming specific account privileges. SHOW GRANTS displays USAGE to indicate that an account has no privileges at a privilege level."

**Comment by carlad** [comment]
Another possible report here: 
https://secure.helpscout.net/conversation/411368038/57986/?folderId=30784
```
09:58:12 ERROR     [console] Error thrown while running command "doctrine:database:create".                                                                              
 [Doctrine\DBAL\Exception\ConnectionException]                              
 An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused  
                         
  [Doctrine\DBAL\Driver\PDOException]        
  SQLSTATE[HY000] [2002] Connection refused  
                               
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused                                           
```

**Comment by Lyoness** [comment]
Ran a build on `group: dev` on sudo: required based on an image stack successfully built with  https://github.com/travis-ci/travis-cookbooks/pull/881

It gave us the proper permissions for all the needed users & hosts: YYYYYYYYYYYYYYYYYYYYY 

https://travis-ci.org/Lyoness/travis_production_test/builds/264938231

**Comment by Lyoness** [comment]
Changes have been merged 
Packer-templates: https://github.com/travis-ci/packer-templates/pull/479
travis-cookbooks: https://github.com/travis-ci/travis-cookbooks/pull/881

All `sudo: required` trusty images with this fix will be available in prod with `group: edge`, we plan to promote the docker images :soon: , typically have an image refresh period of 1st Wednesday of the month, but we can try to see if an image rollout can be done sooner than that.
