### ISSUE TITLE
Pre-install PyPy and PyPy3

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#471]
https://github.com/travis-ci/travis-ci/issues/8081 reports that they are missing from the recent Trusty images.

**Comment by Lyoness** [comment]
Pypy only available in `sugilite`.  

Issue in issue #8081 --  `lang: python` and `dist: trusty` are getting re-routed to `garnet`.  :thinking: 

https://github.com/travis-ci/travis-ci/issues/8081#issuecomment-318179899

**Comment by Lyoness** [comment]
This has been fixed in https://github.com/travis-ci/travis-build/pull/1088
