### ISSUE TITLE
Trusty GCE image is missing mercurial

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#480]
EC2 image is OK. See https://github.com/travis-ci/travis-ci/issues/8202#issuecomment-322637202.

**Comment by Lyoness** [comment]
I'm going to close this for now, as `mercurial` is available for Trusty everywhere, just with a different PATH

https://travis-ci.org/Lyoness/travis_production_test/builds/265980902
https://github.com/travis-ci/travis-ci/issues/8202#issuecomment-323735375

Trying to sort out the sources of installation in different environs was a time sink, we'll put it in the backlog to sort out.
