### ISSUE TITLE
rabbitmq_spec.rb is intermittently failing with 'expected "" to include "my-test-queue"'

### ISSUE THREAD

**Issue by edmorley** [travis-ci/packer-templates#493]
In this job, all three retries of `travis_retry bundle exec ...` failed:
https://travis-ci.org/travis-ci/packer-templates/builds/267569325#L3961

In this job, the first attempt failed, but the next one succeeded:
https://travis-ci.org/travis-ci/packer-templates/builds/267574069#L1945

Both with this failure:
```
rabbitmq installation
  rabbitmqadmin commands
    Command "/tmp/packer-templates-20170823-8612-1ki1fh8-rspec/rabbitmqadmin list queues"
      stdout
        should include "my-test-queue" (FAILED - 1)

...

Failures:

  1) rabbitmq installation rabbitmqadmin commands Command "/tmp/packer-templates-20170823-8612-1ki1fh8-rspec/rabbitmqadmin list queues" stdout should include "my-test-queue"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected "" to include "my-test-queue"
       bash -c /tmp/packer-templates-20170823-8612-1ki1fh8-rspec/rabbitmqadmin\ list\ queues
```

The two jobs above are for completely different PRs, the former updating PHP and the latter Python to newer point releases. I'm struggling to see how they are related, so I think this might be an intermittently failing test, that's been hidden until now by the use of `travis_retry`.

The test in question is here:
https://github.com/travis-ci/packer-templates/blob/9c6875413a5395c4c4dbfcbc1eeb7569e3e35b1b/cookbooks/lib/features/rabbitmq_spec.rb#L41-L44

**Comment by Lyoness** [comment]
Hi @edmorley we do indeed get quite a bit of these intermittent/flaky failures during build time, and can never replicate the error or pinpoint the cause. Network?  I typically restart the build and :eyes: on it.  If it is a consistent failure (consistent = `N` times where `N` is your frustration threshold repeats crossed)

**Comment by edmorley** [comment]
The test in this case has a `sleep 2` in the `before :all` setup function, so I'm guessing this is perhaps just a race condition that manifest depending on the underlying infra load. I wonder if there's another check that could be performed instead of the sleep to make it more deterministic?

**Comment by edmorley** [comment]
I haven't seen this for a while :-)
