### ISSUE TITLE
Pre-install PHP 7.1.x

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/packer-templates#502]
It's been out for a while. It'll be great to have it for the next update.

See https://github.com/travis-ci/travis-ci/issues/7721.

**Comment by edmorley** [comment]
Currently sugilite installs PHP 5.4, 5.5, 5.6 and 7.0, with garnet (+sardonyx) only installing 5.6 and 7.0.

In world where sugilite doesn't exist, should garnet start installing a greater number of PHP versions, or should 7.1 replace 7.0?

(I guess this question applies to several other language runtimes as well - for example sugilite installs 5 different nodejs versions, but garnet only installs 2.)

**Comment by bogdanap** [comment]
Fixed in https://github.com/travis-ci/packer-templates/pull/552
