### ISSUE TITLE
docker server will not start

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/packer-templates#506]
The exact error is:

```
`docker daemon` is not supported on Linux. Please run `dockerd` directly
```

I believe this means that the override upstart template we add via tfw requires an update a la:

``` diff
--- a/etc/init/docker.conf
+++ b/etc/init/docker.conf
@@ _ @@
- exec $DOCKER daemon $DOCKER_OPTS
+ exec dockerd $DOCKER_OPTS

**Comment by edmorley** [comment]
My apologies if this was fallout from travis-ci/travis-cookbooks#892.
Is there a way to test the tfw build like for the other images, for the future?

**Comment by meatballhat** [comment]
@edmorley No worries!  This one is definitely not covered by current testing.  I'm going to shore up `tfw` so that we at least make sure that docker comes up before considering the image baked.
