### ISSUE TITLE
Upgrade tfw to 16.04[+]

### ISSUE THREAD

**Issue by soulshake** [travis-ci/packer-templates#538]
The `tfw` worker AMI should be upgraded to at least Ubuntu 16.04.

## Extra context

`tfw` worker AMI currently has an old `devicemapper` version:

```
# docker info
Storage Driver: devicemapper
 [...]
 Library Version: 1.02.77 (2012-10-15)
```

```
# lvm version
  LVM version:     2.02.98(2) (2012-10-15)
  Library version: 1.02.77 (2012-10-15)
  Driver version:  4.37.0
```

```
# dmsetup --version
Library version:   1.02.77 (2012-10-15)
Driver version:    4.37.0
```

According to https://github.com/moby/moby/issues/35408#issuecomment-342161059, the old devicemapper version may be a contributing factor on that Docker issue. Upgrading to 16.04 will also let us upgrade the devicemapper library.

### References

- [Here](https://github.com/travis-ci/packer-templates/blob/e019fad219e2e8af3202491577d97c879f0ed290/cookbooks/travis_tfw/recipes/default.rb#L32-L35) is where we install `lvm2`.

**Comment by BanzaiMan** [comment]
The upgrade had an unexpected side effect, which manifested in Chrome sandboxing failure (https://github.com/travis-ci/travis-ci/issues/8836).

**Comment by meatballhat** [comment]
@BanzaiMan do you know if this has been verified as a Xenial-only issue?

**Comment by BanzaiMan** [comment]
@meatballhat To the best of my knowledge, yes. The issue does not manifest on Trusty hosts, but does on Xenial ones. See the (long) thread here: https://travisci.slack.com/archives/C0E7ZS68Y/p1512068542000465

**Comment by soulshake** [comment]
Running `google-chrome-stable` on the image tagged `6e0174c4af10` results in different behavior on trusty and xenial worker hosts.

## in 14.04 trusty

In 14.04, `google-chrome-stable` just exits `1` after a few seconds' delay:

```
root@i-00a58ff-production-2-worker-org-ec2:~# docker run -ti 6e0174c4af10 google-chrome-stable
root@i-00a58ff-production-2-worker-org-ec2:~# echo $?
1
root@i-00a58ff-production-2-worker-org-ec2:~# lsb_release -rc
Release:	14.04
Codename:	trusty
```

## in 16.04 xenial

In 16.04 `google-chrome-stable` exits `134` (128+6, 6 = `SIGABRT`):

```
root@6761daf03b20:/# google-chrome-stable 
[16:16:1130/221804.334743:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
Aborted (core dumped)
```

## in both

Permissions are identical on the file mentioned in the error message on both trusty and xenial hosts:

```
-rwxr-xr-x 1 travis travis 14520 Aug 23 03:17 /opt/google/chrome/chrome-sandbox
```

I can't see any difference in apparmor at first glance (but need to figure out where to dig further):

```
# apparmor_status
apparmor module is loaded.
apparmor filesystem is not mounted.
```

If there are any apparmor profiles in use, I don't know where to find them. There's no /etc/apparmor.d/ at all.

If apparmor was catching things, it would show up in the kernel log (I think, at least with reasonable profiles). I didn't see anything obviously apparmor-related in `dmesg` at first glance.

What else might be different between xenial and trusty in terms of kernel, cgroup setup...?

**Comment by meatballhat** [comment]
Done!
