### ISSUE TITLE
Document .test-branch

### ISSUE THREAD

**Issue by edmorley** [travis-ci/packer-templates#543]
In order to test travis-cookbooks changes before landing, the cookbooks branch needs to be overridden. For people not calling `packer-build-trigger` directly, this is done by creating a `.test-branch` file in the packer-templates repo root, that contains the name of the travis-cookbooks branch to use instead of `master`. Note this branch must be on the upstream travis-ci/cookbooks repo, not a fork.

It would be good to document this in:
https://github.com/travis-ci/packer-templates#testing-cookbook-changes

I'll try to find time to open a PR for this at some point.

**Comment by bogdanap** [comment]
I really dislike using `.test-branch` and modifying the templates (like https://github.com/travis-ci/packer-templates/pull/542/files) as a method of triggering test builds and would like us to move away from it.

I think that for now, using `./bin/packer-build-cookbooks-branch` for travis-cookbooks branches is good alternative and already documented in https://github.com/travis-ci/packer-templates#testing-cookbook-changes (I do agree that this particular section of the README needs improvements)

**Comment by edmorley** [comment]
I agree those scripts look like a nicer way of triggering builds, however they require `GITHUB_API_TOKEN` to be set, which as a non-employee I don't have. (Extracting the credential via my commit access to this repo would be a little rude.. hehe)

**Comment by edmorley** [comment]
> however they require GITHUB_API_TOKEN to be set

The workaround I've come up with (which also fixes trigger-packer-builds not picking up the correct changes 50%+ of the time), is to replace the entire `script` and `after_success` sections with this, where the image types are manually specified:

```yaml
script:
- export TRAVIS_COOKBOOKS_TEST_BRANCH='<custom-cookbooks-branch>'
- export TRAVIS_COMMIT_RANGE='@...@'
- bundle exec ./bin/packer-build-trigger -I ci-connie.yml
```

eg:
https://travis-ci.org/travis-ci/packer-templates/builds/299805821#L650
