### ISSUE TITLE
Using `language: generic` in .travis.yml currently results in an old sugilite image

### ISSUE THREAD

**Issue by bogdanap** [travis-ci/packer-templates#550]
Initially raised [here](https://github.com/travis-ci/packer-templates/pull/498#issuecomment-343926802)

With the removal of sugilite, we should be now tagging garnet with `language: generic`

**Comment by bogdanap** [comment]
Fixed by https://github.com/travis-ci/packer-templates/pull/564 and some manual tagging.

**Comment by edmorley** [comment]
Does sardonyx also need to be tagged with `generic`, such that users who switch from `dist: trusty` to `dist xenial` continue to get the correct images? Or will the lack of a Xenial image with the `generic` tag mean they just get the default Xenial image (which will presumably be sardonyx anyway).
