### ISSUE TITLE
PHP is installed into Amethyst/Opal when it possibly shouldn't

### ISSUE THREAD

**Issue by edmorley** [travis-ci/packer-templates#578]
Broken out from #549.

The PHP tagged images are Garnet/Sardonyx. However 3 versions of PHP are also installed into Amethyst/Opal as well, since they inherit the config from travis-cookbooks and don't override like connie/stevonnie do. 

Even if it's intended for Amethyst/Opal to have *a* PHP version, perhaps they don't need 3 versions?

(Also - perhaps opt-in rather than opt-out configs would make this harder to occur?)

**Comment by edmorley** [comment]
Even if this was intended for Trusty, perhaps Xenial is a good time to make this breaking change?

**Comment by joepvd** [comment]
Resolved for Xenial
