### ISSUE TITLE
File permissions just gone up to 664

### ISSUE THREAD

**Issue by szepeviktor** [travis-ci/packer-templates#672]
Could it be that files right after git clone+git checkout have 664 permissions instead of 644?

Up to today it was 644.

See https://travis-ci.org/nunomaduro/larastan/jobs/470628881#L462

Thank you.

**Comment by meatballhat** [comment]
@szepeviktor Please see the comment I left on travis-ci/worker#577

**Comment by szepeviktor** [comment]
@meatballhat I am sorry.

The forum says _Account temporarily on hold_

**Comment by DrTorte** [comment]
Hey there,

So sorry that occurred. One of the default settings seemed to block first messages if they were typed too fast - intended to stop spam bots, but could potentially be triggered by human users. 

I've changed the tolerances for that setting, and also made sure we're more clearly notified if it does occur. 

Thanks and all the best,

Kris

**Comment by szepeviktor** [comment]
@DrTorte Thank you.
